// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"loginserver/internal/biz"
	"loginserver/internal/conf"
	"loginserver/internal/data"
	"loginserver/internal/server"
	"loginserver/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData, logger)
	fmt.Println(accountRepo)
	accountUsecase := biz.NewAccountUsecase(accountRepo, logger)

	userCounterRepo := data.NewUserCounterRepo(dataData, logger)
	userCounterUsecase := biz.NewUserCounterUsecase(userCounterRepo, logger)
	fmt.Println(userCounterUsecase)
	accountService := service.NewAccountService(accountUsecase, logger)
	fmt.Println(accountService)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
